<a href="https://colab.research.google.com/github/YashKerkar211/Data-Science-Programs/blob/main/BasicPy%26Np_Pd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x=5
m=6
y="9"
z="2"
print(type(x))
print(type(y))
print(x+m)
print(y+z)

<class 'int'>
<class 'str'>
11
92


In [ ]:
#typecasting
a=int(z)
print(a+m)
''' is used for
multi line
comment  '''

8


' is used for \nmulti line\ncomment  '

In [ ]:
# List:- ordered collection of items, changeable, it allows duplicate values
l1=[56,"hello",True,56.2,["Yash","Viraj"]]
print(l1)
l2=l1[4][-2][0:3]
print(l2)
print(len(l1))
print(len(l2))
l1.append("Shlok")
l1.insert(1,"Ankit")
l1.pop(2)
print(l1)

[56, 'hello', True, 56.2, ['Yash', 'Viraj']]
Yas
5
3
[56, 'Ankit', True, 56.2, ['Yash', 'Viraj'], 'Shlok']


In [ ]:
#Tuple: It is a immutable dataype.
t1=(6,7,"Yash")
print(t1)

(6, 7, 'Yash')


In [ ]:
#Dict
d1={"Name":"Yash","Proff":"Student"}
print(d1.keys())
print(d1.items())
print(d1.values())
print(d1['Name'])

dict_keys(['Name', 'Proff'])
dict_items([('Name', 'Yash'), ('Proff', 'Student')])
dict_values(['Yash', 'Student'])
Yash


In [ ]:
#input
num1=int(input("Enter a number:"))
a=input("Enter the operator (+,-)")
num2=int(input("Enter second number:"))
if a=="+":
  print(num1+num2)
elif a=='-':
  print(num1-num2)
else:
  print("Invalid")

Enter a number:5
Enter the operator (+,-)-
Enter second number:2
3


In [ ]:
#Numpy
import numpy as np

# Array with rank 1
arr=np.array([[7,8,9]])
# Array with rank 2
arr=np.array([[7,8,9] ,["hello",True,56.7]])

#Printing array
print(arr)

#Printing array dimensions (axes)
print("No. of dimensions",arr.ndim)

#Printing shape of array
print("Shape of array:",arr.shape)

#Printing size (total number of elements) of array
print("Size of array:",arr.size)

#Printing type of elements in array
print("Array stores elements of type:",arr.dtype)
print("Array is of type:",type(arr))

# Creating an array from tuple
arr=np.array((1,3,2))
print(type(arr))

[['7' '8' '9']
 ['hello' 'True' '56.7']]
No. of dimensions 2
Shape of array: (2, 3)
Size of array: 6
Array stores elements of type: <U32
Array is of type: <class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

#creating array
arr=np.array([2,4,6,8,10])

#creating copy of array
c=arr.copy()

#both arr and c have different id
print("id of arr",id(arr))
print("id of c",id(c))

#changing original array
#this will not affect copy
arr[0]=67

#printing array and copy
print("original array:",arr)

print("copy:",c)

id of arr 135276492602032
id of c 135276492933040
original array: [67  4  6  8 10]
copy: [ 2  4  6  8 10]


In [ ]:
def sum(array):
  sum=0
  for i in array:
    sum+=i
  return sum

testArray=[1,2,3,4]

print('The sum of your number is '+str(sum(testArray)))

The sum of your number is 10


In [ ]:
import numpy as np
a=np.arange(10,1,-2)
newarr=a[np.array([3,1,2])]  #fancy indexing in numpy
print("\n Element at these indices are:\n",newarr)


 Element at these indices are:
 [4 8 6]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#The result includes the start index, but excludes the end index

import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
#The copy is not affected by the changes made to the original array
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#The copy is affected by the changes made to the original array
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#Check if array owns its data
#copies owns the data, and views does not own the data

import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
#Create an array with 5 dimensions using ndim
#using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np

arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

newarr=arr.reshape(2,3,2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

x=np.array([[1,2],[4,5]])
y=np.array([[7,8],[9,10]])
print(np.add(x,y))
print()
print(np.subtract(x,y))
print()
print(np.multiply(x,y))
print()
print(np.divide(x,y))

[[ 8 10]
 [13 15]]

[[-6 -6]
 [-5 -5]]

[[ 7 16]
 [36 50]]

[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [ ]:
import pandas as pd

mydataset={
    'Owner Name':"Yash Kerkar",
    'Cars':["BMW","Lambo"]
}

myvar=pd.DataFrame(mydataset)
print(myvar)

    Owner Name   Cars
0  Yash Kerkar    BMW
1  Yash Kerkar  Lambo


In [ ]:
#Version string of Pandas
import pandas as pd
print(pd.__version__)

2.0.3


In [ ]:
#a pandas series is like a column in a table
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a)
print(myvar)
print(myvar[1])

0    1
1    7
2    2
dtype: int64
7


In [ ]:
import pandas as pd
a=["India","America","UK"]
myvar=pd.Series(a,index=["a","b","c"])
print(myvar)
print(myvar['a'])

a      India
b    America
c         UK
dtype: object
India


In [ ]:
import pandas as pd
data={
    "calories":[420,340,780],
    "duration":[50,40,80]
}

#load data into a DataFrame object:
df=pd.DataFrame(data)
print(df)

#Pandas use the loc attribute to return one or more specified rows
print(df.loc[0])
print(df.loc[1])

   calories  duration
0       420        50
1       340        40
2       780        80
calories    420
duration     50
Name: 0, dtype: int64
calories    340
duration     40
Name: 1, dtype: int64


In [ ]:
import pandas as pd
df=pd.read_csv('Data.csv')
print(df.to_string())
#use to_string to print entire dataframe

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
#If you have a large DataFrame with many rows, pandas will only return and first and last 5 rows
import pandas as pd
df=pd.read_csv('Data.csv')
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
import pandas as pd
print(pd.options.display.max_rows)
# The number of rows returned is defined in Pandas option settings.

60


In [ ]:
import pandas as pd
pd.options.display.max_rows=9999
df=pd.read_csv('Data.csv')
print(df)
print(pd.options.display.max_rows)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
9999


In [ ]:
#Load a Python dictionary into a DataFrame     JSON=Python Dictionary

import pandas as pd

data={
    "Duration":{
        "0":60,
        "1":60,
        "2":60,
        "3":60,
        "4":60,
        "5":60,
        "6":60,
        "7":60
    },
     "Pulses":{
        "0":110,
        "1":117,
        "2":103,
        "3":109,
        "4":117,
        "5":102
    },
     "Maxpulse":{
        "0":130,
        "1":145,
        "2":135,
        "3":175,
        "4":148,
        "5":127,
    },
     "Calories":{
        "0":409,
        "1":479,
        "2":340,
        "3":282,
        "4":406,
        "5":300
    }
}

df=pd.DataFrame(data)
print(df)

   Duration  Pulses  Maxpulse  Calories
0        60   110.0     130.0     409.0
1        60   117.0     145.0     479.0
2        60   103.0     135.0     340.0
3        60   109.0     175.0     282.0
4        60   117.0     148.0     406.0
5        60   102.0     127.0     300.0
6        60     NaN       NaN       NaN
7        60     NaN       NaN       NaN


In [ ]:
import pandas as pd

#creating first dataframe
df1=pd.DataFrame({"fruit":["apple","banana","mango"],
                  "market_price":[21,34,50]})
display("The first dataframe")
display(df1)

#creating second dataframe

df2=pd.DataFrame({"fruit":["banana","apple","strawberry"],
                 "wholesaler_price":[56,78,90]})
display("The second dataframe")
display(df2)

# Joining two DataFrames
display("The merged DataFrame:")
pd.merge(df1,df2,on="fruit",how="inner")
# how; {'left','right','outer','inner'}

'The first dataframe'

fruit  market_price
0   apple            21
1  banana            34
2   mango            50

'The second dataframe'

fruit  wholesaler_price
0      banana                56
1       apple                78
2  strawberry                90

'The merged DataFrame:'

fruit  market_price  wholesaler_price
0   apple            21                78
1  banana            34                56

In [ ]:
#groupby() function is used to split the data into groups based on some criteria.
#Pandas objects can be split on any of their axes

import pandas as pd

#Creating the Dataframe
df=pd.read_csv("Cancer_data.csv")

print(df.head()) # head returns top 5 rows by default

   Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
0   58       1  16.085313        0            1          8.146251   
1   71       0  30.828784        0            1          9.361630   
2   48       1  38.785084        0            2          5.135179   
3   34       0  30.040296        0            0          9.502792   
4   62       1  35.479721        0            0          5.356890   

   AlcoholIntake  CancerHistory  Diagnosis  
0       4.148219              1          1  
1       3.519683              0          0  
2       4.728368              0          1  
3       2.044636              0          0  
4       3.309849              0          1  


In [ ]:
gk=df.groupby('GeneticRisk')
gk.first()

Age  Gender        BMI  Smoking  PhysicalActivity  AlcoholIntake  \
GeneticRisk                                                                     
0             34       0  30.040296        0          9.502792       2.044636   
1             58       1  16.085313        0          8.146251       4.148219   
2             48       1  38.785084        0          5.135179       4.728368   

             CancerHistory  Diagnosis  
GeneticRisk                            
0                        0          0  
1                        1          1  
2                        0          1

In [ ]:
gk.get_group(1).head()

Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
0   58       1  16.085313        0            1          8.146251   
1   71       0  30.828784        0            1          9.361630   
5   27       0  37.105162        0            1          3.941905   
8   58       1  30.274525        0            1          4.719025   
9   77       0  25.275712        0            1          4.903125   

   AlcoholIntake  CancerHistory  Diagnosis  
0       4.148219              1          1  
1       3.519683              0          0  
5       2.324274              0          0  
8       0.943161              1          1  
9       2.539487              0          0

In [ ]:
#Indentation
j=1
while(j<=7):
  print(j)
  j+=1

  if(j==5):
      break

1
2
3
4
